[tool.poetry]
name = "operationgreenmonkey"
version = "0.1.0"
description = "Green  Money Green Monkey"
authors = ["YungGriff"]
license = "N/A"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
